name: todoapp
description: "Aplicación Flutter de lista de tareas con almacenamiento local."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Base de datos local
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.19.0

  # State management
  provider: ^6.1.0

  # Utilidades
  uuid: ^4.0.0
  get: ^4.6.6

  # Notificaciones
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
